### ISSUE TITLE
Feature Request: Feeds for multiple collections

### ISSUE THREAD

**Issue by k-funk** [jekyll/jekyll-feed#128] opened 2016-09-06 19:57 UTC
Right now I can access my collections at `site.collections['blog_posts']`, `site.collections['changelog_items']`, I'd like to be able to create a feed for each:

* `blog-feed.xml`
* `changelog-feed.xml`

**Comment by pathawks** [comment] 2016-09-06 20:05
Closing as a duplicate of #124

Let's keep the discussion going over there :+1:

**Closed by pathawks** 2016-09-06 20:05 UTC
