### ISSUE TITLE
Mailchimp (and Feedburner) does not render images

### ISSUE THREAD

**Issue by Dovizu** [jekyll/jekyll-feed#296] opened 2020-01-17 18:06 UTC
According to Mailchimp, feeds need a <media:content> tag to display images. Images in Mailchimp are displayed with their relative paths.

**Comment by Dovizu** [comment] 2020-01-17 18:07
Also, feeds generated by this plugin do not validate in http://validator.w3.org/

**Comment by DirtyF** [comment] 2020-01-17 21:45
Duplicate of #275
Duplicate of #273 
Duplicate of #290

**Closed by DirtyF** 2020-01-17 21:45 UTC

**Comment by Dovizu** [comment] 2020-01-17 22:20
Hmm, that’s odd. I am using v0.13 but my feed still doesn’t have this tag in Mailchimp. 
https://b-side.donny.io/feed.xml
Am I configuring something wrong?

**Comment by DirtyF** [comment] 2020-01-17 23:50
Are use using an `image` property in your front matter?

See https://github.com/fractalsoft/jekyll-feed/blob/1b8a1680ff0d302d8dbae90dbc03ac574038fdb5/lib/jekyll-feed/feed.xml#L86-L93

**Comment by Dovizu** [comment] 2020-01-18 00:16
No, I’m referring to the images inside the posts.

**Comment by Dovizu** [comment] 2020-02-05 16:55
Circling back to this. I understand that the image property in the post front matter is used for _single_ images, and not for the images within the body of the post. My problem isn't with the post single images (I never set those), but the images inside the body not being shown in MailChimp. 

MailChimp support also points to the fact that the generated feed does not validate. Although I don't think that has much to do with this problem. 
https://validator.w3.org/feed/check.cgi?url=b-side.donny.io%2Ffeed.xml

**Comment by Dovizu** [comment] 2020-03-29 20:24
Friendly ping again.
